language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
sudo: required

script:
- swift --version
- xcodebuild -version
- xcodebuild -project TDLikertScaleSelectorView.xcodeproj -scheme TDLikertScaleSelectorViewTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS,OS=12.0" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
- xcodebuild -project TDLikertScaleSelectorView.xcodeproj -scheme TDLikertScaleSelectorViewUITests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XS,OS=12.0" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
