language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
sudo: required

script:
- swift --version
- swift package update
- swift test
- xcodebuild -version
- xcodebuild -project TDLikertScaleSelectorView.xcodeproj -scheme TDLikertScaleSelectorViewTests -sdk iphonesimulator -destination "OS=12.0,name=iPhone 8" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
- xcodebuild -project TDLikertScaleSelectorView.xcodeproj -scheme TDLikertScaleSelectorViewUITests -sdk iphonesimulator -destination "OS=12.0,name=iPhone 8" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
