language: objective-c
osx_image: xcode9.4
xcode_sdk: iphonesimulator11.4
script:
- xcodebuild -version
- xcodebuild -project TDLikertScaleSelectorView/TDLikertScaleSelectorView.xcodeproj -scheme TDLikertScaleSelectorViewTests -sdk iphonesimulator -destination "OS=11.4,name=iPhone 8" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
- xcodebuild -project TDLikertScaleSelectorView/TDLikertScaleSelectorView.xcodeproj -scheme TDLikertScaleSelectorViewUITests -sdk iphonesimulator -destination "OS=11.4,name=iPhone 8" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
